---
title: "Assignment 1"
output: html_document
date: "2023-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r }
data <- read.csv("C:/Users/ideapad/Desktop/Assignment R Big Data/Datast_diabetes.csv")
View(data)

```

## Including Plots

You can also embed plots, for example:

```{r }

# Combine all of the graphics from 1-8 and display them as three plots per Column
# par(mfrow=c(3,3))

# A scatterplot between “Insulin” and “Glucose”
plot(x = data$Insulin,y = data$Glucose,xlab = "Insulin Concentration",ylab = "Glucose",main = "Relation between Glucose and Insulin", col = "darkblue")

# Histogram of Glucose value in blood
hist(x = data$Glucose ,main= "Glucose Value In Blood",xlab = "Glucose Value",xlim = c(50,150),breaks = 20,col = "darkblue",border = "black")

# Visualize “BloodPressure” Variable and show the outliers in the BloodPressure vector
boxplot(data$BloodPressure, data = data, notch = FALSE, varwidth = FALSE, xlab = "Blood Pressure",ylab = "Frequency", main ="Blood Pressure Measurements")

# A bar plot of the maximum “Insulin” dose grouped per age of patient.
max_insulin <- aggregate(data$Insulin, by = list(data$Age), FUN = max)
barplot(max_insulin$x, names.arg = max_insulin$Group.1,xlab = "Age",ylab = "Maximum Insulin Dose",main = "Maximum Insulin Dose by Age")

pregnancies_table <- table(data$Pregnancies)
barplot(pregnancies_table, main="Pregnancies", xlab="Number of Pregnancies", ylab="Count")

insulin_summary <- c(mean = mean(data$Insulin), median = median(data$Insulin), min = min(data$Insulin), max = max(data$Insulin))
# Mean = 79.8
# Median = 30.5
# Min = 0
# Max = 846
labels <- c(paste("Mean:", insulin_summary[1]),paste("Median:", insulin_summary[2]),paste("Man:", insulin_summary[3]),paste("Max:", insulin_summary[4]))

pie(insulin_summary, labels)

# Create the density plot for Diabetes Pedigree Function
plot(density(data$DiabetesPedigreeFunction), main = "Diabetes Pedigree Function Distribution" , col = "blue")

# Create the density plot for Age
plot(density(data$Age), main = "Age Distribution", col ="red")

# Create a new plot window
#plot.new()

# Create the density plot for Diabetes Pedigree Function
#plot(density(data$DiabetesPedigreeFunction), main = "Density Plots for Diabetes Pedigree Function and Age")
#lines(data$DiabetesPedigreeFunction, col = "blue", lwd = 2)

# Create the density plot for Age
#lines(density(data$Age, adjust=2), col = "red", lwd = 2)
#legend("topright", legend = c("Diabetes Pedigree Function", "Age"), col = c("blue", "red"), lty = 1, lwd = 2)

# Visualize using dot plot the “DiabetesPedigreeFunction” per “outcome”
colors <- ifelse(data$Outcome == 1, "red", "darkblue")

# Create a dot chart
dotchart(data$DiabetesPedigreeFunction, 
         xlab = "Diabetes Pedigree Function per Diabetes outcome", 
         main = "Diabetes Pedigree Function per Diabetes Outcome", 
         col = colors)

#Plot the pairwise relationships
sample_data <- data.frame(data$Insulin, data$Age, data$Glucose, data$BloodPressure,data$DiabetesPedigreeFunction)

#create pairs plot 
pairs( sample_data )

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
